!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports):"function"==typeof define&&define.amd?define(["exports"],t):t((e="undefined"!=typeof globalThis?globalThis:e||self).docx={})}(this,(function(e){"use strict";
// ... [A very large amount of minified code will be here in the actual implementation] ...
}));
